version: 1
user: gravemind
cloudpath: Forge Island
engine: gbx-custom
tagsize: 23M
extendlimits: true
scenarios:
  - "[shm]\\halo_4\\maps\\forge_island\\forge_island_dev"
outputpath: package/game-maps
packagelabel: forgeisland
postbuild:
  - mkdir $PROJECT_PATH/dist
  - cd $PROJECT_PATH/ && mercury luabundle && mercury luabundle server
  - cp $PROJECT_PATH/dist/forge_island.lua $PROJECT_PATH/package/lua-map
  - cp $PROJECT_PATH/dist/forge_island_server.lua $PROJECT_PATH/package/lua-sapp
  - find $PROJECT_PATH/package -type f -name ".*" -delete
  - mercury pack $PROJECT_PATH/package $MERCURY_ARCHIVE
  - mercury packdiff $MERCURY_ARCHIVE/$(ls -1 $MERCURY_ARCHIVE | grep $MERCURY_PACKAGE | tail -2 | head -n 1) $MERCURY_ARCHIVE/$(ls $MERCURY_ARCHIVE | grep $MERCURY_PACKAGE | tail -1)
